version: "3.8"
services:
  komga-kindle:
    build:
      context: .
      dockerfile: Dockerfile
    image: komga-kindle:latest
    ports:
      - "25600:25600"
    volumes:
      # Config Folder
      - type: bind
        source: /mnt/dockerHDD/opt/komga
        target: /config
      # Library Folder      
      - type: bind
        source: /mnt/mainHDD
        target: /data
      - type: bind
    env_file:
      - .env
    environment:
#      - KOMGA_LIBRARIES_PATHS=/data
      - SPRING_PROFILES_ACTIVE=prod
      # Kindle configuration - adjust as needed
      - KINDLE_IP=${KINDLE_IP}
      - KINDLE_USER=${KINDLE_USER}
      - KINDLE_REMOTE_PATH=${KINDLE_REMOTE_PATH}
      - KINDLE_SSH_PASSWORD=${KINDLE_SSH_PASSWORD}
      - KINDLE_SSH_PORT=${KINDLE_SSH_PORT}
    restart: unless-stopped