#!/usr/bin/env python3
"""
process_outsource.py - Tool for processing LLM-generated technical specifications

This script processes "outsource.md" files that contain technical specifications
generated by Large Language Models (LLMs). It extracts file references from the
specification and inserts the actual source code into the output document.

The script is designed to work with the "Outsourcer" mode workflow, where:
1. An LLM generates technical specifications in outsource.md format
2. This script processes the specification by inserting actual source code
3. The resulting document can be used for code review or implementation

OUTSOURCE.MD FORMAT:
The input file should follow this pattern:
```
### File: path/to/file.ext
Description of what this file does and what changes are needed

### File: another/path/file.ext
Description of another file and its requirements
```

EXAMPLE PROMPT FOR LLM:
When using this with an LLM in Outsourcer mode, use prompts like:

"Generate a technical specification for adding a new feature to Komga.
Create an outsource.md document that includes:
1. File paths that need to be modified or created
2. Detailed descriptions of what each file should contain
3. Required changes to existing code
4. New data structures and API endpoints
5. Expected user interface changes
6. The original error log

Format the output using the pattern:
### File: path/to/file.ext
Description of what this file does and required changes

### File: another/path/file.ext
Description of another file and its requirements"

USAGE SCENARIOS:
1. Code Review: Generate comprehensive documentation with actual code snippets
2. Implementation Guide: Create step-by-step instructions with code examples
3. Technical Documentation: Combine specifications with real codebase context
4. Outsourcing: Provide complete context to external developers or LLMs

TYPICAL WORKFLOW:
1. Use LLM to generate outsource.md with technical specifications
2. Run: python process_outsource.py outsource.md outsource_source_code.md
3. Review the generated outsource_source_code.md file
4. Use the documented specifications for implementation or further LLM processing
"""

import re
import os
import sys

def get_language_from_extension(file_path):
    """
    Determine the programming language based on file extension.
    
    Args:
        file_path (str): Path to the file
        
    Returns:
        str: Language identifier for code block formatting
    """
    extension = os.path.splitext(file_path)[1].lower()
    
    language_map = {
        '.py': 'python',
        '.kt': 'kotlin',
        '.java': 'java',
        '.js': 'javascript',
        '.ts': 'typescript',
        '.vue': 'vue',
        '.html': 'html',
        '.css': 'css',
        '.scss': 'scss',
        '.sass': 'sass',
        '.xml': 'xml',
        '.json': 'json',
        '.yaml': 'yaml',
        '.yml': 'yaml',
        '.md': 'markdown',
        '.sh': 'bash',
        '.bash': 'bash',
        '.gradle': 'groovy',
        '.properties': 'properties',
        '.sql': 'sql',
        '.dockerfile': 'dockerfile',
        '.dockerignore': 'dockerignore',
        '.gitignore': 'gitignore',
        '.txt': 'text',
        '.rst': 'restructuredtext',
        '.c': 'c',
        '.cpp': 'cpp',
        '.h': 'c',
        '.hpp': 'cpp',
        '.cs': 'csharp',
        '.go': 'go',
        '.rs': 'rust',
        '.rb': 'ruby',
        '.php': 'php',
        '.swift': 'swift',
        '.m': 'objectivec',
        '.mm': 'objectivec',
    }
    
    return language_map.get(extension, 'text')

def process_outsource(input_file, output_file):
    """
    Process an outsource.md file by inserting actual source code from referenced files.
    
    This script reads an outsource.md file containing technical specifications with
    file references, and generates a new file with the actual source code inserted
    after each file description.
    
    Args:
        input_file (str): Path to the input outsource.md file
        output_file (str): Path to the output file with inserted source code
    
    Returns:
        None: Writes the processed content to output_file
    """
    # Read the input file
    with open(input_file, 'r') as f:
        content = f.read()

    # Extract file paths and their descriptions using regex pattern
    # Pattern matches: "### File: path/to/file.ext" followed by description text
    file_refs = re.findall(r'### File: (.*?)\n(.*?)(?=###|\Z)', content, re.DOTALL)
    
    # Read each referenced file and insert its content
    for path, description in file_refs:
        try:
            # Clean up path by removing any leading/trailing whitespace
            clean_path = path.strip()
            
            # Check if file exists
            if not os.path.exists(clean_path):
                print(f"Warning: File not found: {clean_path}")
                continue
                
            with open(clean_path, 'r') as f:
                file_content = f.read()
            
            # Determine language based on file extension
            language = get_language_from_extension(clean_path)
            
            # Insert the file content after its description
            insertion_point = content.find(description) + len(description)
            content = content[:insertion_point] + f"\n```{language}\n{file_content}\n```\n" + content[insertion_point:]
        except FileNotFoundError:
            print(f"Warning: File not found: {clean_path}")
            continue
        except Exception as e:
            print(f"Error processing file {clean_path}: {e}")
            continue
    
    # Write the output file
    with open(output_file, 'w') as f:
        f.write(content)
    print(f"Successfully processed {input_file} -> {output_file}")

def print_usage():
    """Print usage instructions for the script."""
    print("""
process_outsource.py - Tool for processing outsource.md files

Usage:
  python process_outsource.py [input_file] [output_file]

Arguments:
  input_file   Path to the input outsource.md file (default: outsource.md)
  output_file  Path to the output file (default: outsource_source_code.md)

Examples:
  # Process default files
  python process_outsource.py
  
  # Process custom files
  python process_outsource.py my_spec.md my_output.md
  
  # Show this help
  python process_outsource.py --help
""")

if __name__ == "__main__":
    # Handle command line arguments
    if len(sys.argv) == 1:
        # Default behavior
        process_outsource("outsource.md", "outsource_source_code.md")
    elif len(sys.argv) == 2:
        if sys.argv[1] in ['--help', '-h']:
            print_usage()
        else:
            process_outsource(sys.argv[1], "outsource_source_code.md")
    elif len(sys.argv) == 3:
        process_outsource(sys.argv[1], sys.argv[2])
    else:
        print_usage()
        sys.exit(1)